version: '0.1'

services:
  cilikube-ui:
    build: ./ui
    container_name: cilikube-ui
    ports:
      - "8888:8888"
    restart: unless-stopped
    networks:
      - cilikube-net

  cilikube-backend:
    build: .
    container_name: cilikube
    ports:
      - "8080:8080"
    environment: # 修改你 kubeconfig 的路径
      - KUBECONFIG=/root/.kube/config
    volumes:
      - /root/.kube:/root/.kube # 挂载 kubernetes 集群在宿主机的路径到容器
      - ./configs:/app/configs
    restart: unless-stopped
    networks:
      - cilikube-net
    depends_on:
      - cilikube-ui

# 网络隔离
networks:
  cilikube-net:
    driver: bridge